# render.yaml
# Defines services for the Fog Detection System monorepo on Render.

services:
  # Backend Service (FastAPI)
  - type: web         # Web service that listens for HTTP requests
    name: fog-backend # Service name on Render
    env: python       # Environment type
    rootDir: backend  # Root directory for this service
    buildCommand: |   # Commands to build the service
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT # Command to start the service ($PORT is injected by Render)
    envVars:
      - key: PYTHON_VERSION
        value: 3.11 # Specify a Python version Render supports
      # Add other backend environment variables here if needed (e.g., MONGO_URI)
      # - key: MONGO_URI
      #   sync: false # Keep sensitive variables out of sync if possible

  # Frontend Service (Next.js)
  - type: web         # CHANGED: Use 'web' for Next.js applications
    name: fog-frontend # Service name on Render
    env: node         # CHANGED: Specify Node.js environment
    rootDir: frontend # Root directory for this service
    buildCommand: |   # Commands to build the service
      npm install --force # Install dependencies
      npm run build     # Build the Next.js app (assuming default 'next build')
    startCommand: npm start # ADDED: Standard command to start a Next.js production server
    envVars:
      # Important: Make the backend URL available to the frontend build process
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService: # Get the URL from the backend service defined above
          type: web
          name: fog-backend
          property: hostport # CHANGED: Trying 'hostport' based on the error message
      # Add other frontend environment variables if needed, like NODE_VERSION
      # - key: NODE_VERSION
      #   value: 18 # Or your desired Node version
